### POST

POST http://localhost:5050/like
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZWJiM2JhODAwMDJ1Z255ZTg2dnJnbGwiLCJuYW1lIjoidXNlcl8yIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTU2MDcwMDgsImV4cCI6MTc1NTYwNzkwOH0.5fItLz8p-hA4r6jbll5Z1Yv_Fk-wQeto_A_MIWvEKKs

{
    "schema": "destinations",
    "schemaId": "cmebb3bb6000pugnyv2xmz0mw"
}


### DELETE

DELETE http://localhost:5050/like/sdsad
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZWJiM2JhODAwMDJ1Z255ZTg2dnJnbGwiLCJuYW1lIjoidXNlcl8yIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTU2MDcwMDgsImV4cCI6MTc1NTYwNzkwOH0.5fItLz8p-hA4r6jbll5Z1Yv_Fk-wQeto_A_MIWvEKKs